### PR TITLE
Move project structure to a more traditional setup.

### PR DESCRIPTION
**Pull request by runningcode**
This makes it so that we only have one gradle project in the repository. I'm looking for feedback on this PR and if this is how we would like to structure the project. I think this makes it much easier to maintain the repository.

There are a couple of advantages to this:
* This makes it easier to open the project in intellij making it easier to
contribute. You don't have to open up multiple projects anymore, the
standard VCS -> Checkout from version control -> git should work.
Or just opening the root project will work.
* Less files in the repository.
* Common configuration such as spotless is more easily and automatically
applied to subprojects.
* Easier to share code and introduce dependencies between projects.
* Easier to assemble any module since anything can now be build from
root.
* Tests and checks can be easily run for the entire repository with one
command.

### CODE REVIEW

**Comment by bootstraponline** [comment]
Thanks for taking the time to submit a pull request. I've reviewed the proposed changes and provided feedback below.

Current structure:




New structure:





## Project Overview

- `test_app` - Android app. Developed using Android Studio
- `apis/testing` - Auto generated Java bindings. No code modifications.
- `junit_html_report` - React web app using TypeScript. Developed using Visual Studio Code.
- `kotlin_poc` - Kotlin desktop app. Developed using IntelliJ IDEA CE.

Current setup means when working on flank, only `kotlin_poc` is loaded (with `apis/testing` as a dependency). In the new setup, everything is loaded all at once. Even on projects that require a different IDE.

I think the proposed changes make it more complex to work on the project by adding all the unrelated projects into a single root view. 99% of changes will only ever happen in `kotlin_poc`

**Comment by runningcode** [comment]
Hey, thanks for taking a look.  :)
I think its the typical setup setup to load all the code and modules in a repository when opening Intellij. I think it makes it easier to explore the repository.
Here are some examples in larger projects: https://github.com/Netflix/conductor
https://github.com/gradle/gradle
https://github.com/diffplug/spotless
I had trouble finding a counter example, but please point me to one if you know of one.

Without this, I think it should be necessary to create a guide on how to open the code in the repository to make it easier for others to contribute.

Also, the setup in this branch makes it very easy to fix the code style and apply code style to the entire project with one command: `./gradlew spotlessApply` instead of applying it to the entire project.
I've updated the PR to address this issue to show how this setup makes it easier to maintain this repository: https://github.com/TestArmada/flank/issues/263

`test_app` can be easily maintained and worked on from Intellij since Intelij and Android Studio are almost the same thing. 
As for `apis/testing`, I think having it in the same intellij project makes it easier to understand what is happening with the code.
For `junit_html_report`, intelij supports json, css and html and I think having it in the same repository makes it nicer and easier to contribute to this code.

But anyways, this is just my perspective based on other open source projects I've contributed to. I'd be interested to hear what others think about this.
At the end of the day, you're the maintainer so I think its best to use whatever works best for you. :) However, I think the current project structure turns off potential contributors since it doesn't automatically work out of the box.

**Comment by bootstraponline** [comment]
> I had trouble finding a counter example, but please point me to one if you know of one.

There's one workspace per app. In a mono repo, all projects are in a single repo. The use case is working on a single project a time so that's how gradle is structured. We wouldn't want to load all Android apps for a company in a single IDE simultaneously for example.

https://github.com/instructure/instructure-android

> , I think it should be necessary to create a guide on how to open the code in the repository to make it easier for others to contribute.

Agreed. I think we want a guide either way. There are currently no docs for Flank Kotlin.

> I'd be interested to hear what others think about this.

I'll ping some of the other Flank contributors.

> Here are some examples in larger projects:

I think the problem with those repos is they're not mono repos. All the code is directly for that one logical project.

> Also, the setup in this branch makes it very easy to fix the code style and apply code style to the entire project with one command:

I agree that's a win.

> I think the current project structure turns off potential contributors since it doesn't automatically work out of the box.

In comparing the screenshots, I'd think the simple version with only the Kotlin code is most attractive to contributors. The remaining parts of the code don't require any changes (test_app/api) and the `junit_html_report` is [not supported in the free IntelliJ](https://www.jetbrains.com/help/idea/typescript-support.html). `test_app` is also a *lot* nicer to work with in Android Studio.

I'll leave the PR open to collect feedback.

**Comment by bootstraponline** [comment]
https://github.com/gradle/kotlin-dsl/tree/master/samples is another counter example.

I'm working on taking the ideas in this PR and cleaning up the overall structure. It'll end up with a build file in the root that loads flank + the api project. I think the html report and android app are best left as isolated projects.

**Comment by bootstraponline** [comment]
I ended up simplifying the structure. There's only one project targeted for contributions `test_runner` and that contains all the necessary gradle files.

Thanks for putting together the pull request. It helped me think about how to restructure the repo for productivity.

root:


test_runner:

**Comment by runningcode** [comment]
Sounds great!

**Pull request closed without merging**
