### PR TITLE
Quiet all gsutil commands

### PR DESCRIPTION
**Pull request by bootstraponline**
```
$ ./e2e_test.sh
:clean
:compileJava
Note: /code/flank/Flank/src/main/java/com/walmart/otto/tools/ProcessBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources NO-SOURCE
:classes
:jar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 0.959 secs
+ java -jar ./build/libs/Flank-1.2.0.jar ../test_app/apks/app-debug.apk ../test_app/apks/app-debug-androidTest.apk

Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 seconds.
$ gsutil --quiet mb gs://delta-essence-114723-flank/
ServiceException: 409 Bucket delta-essence-114723-flank already exists.

Creating bucket: gs://delta-essence-114723-flank/

Uploading: ../test_app/apks/app-debug.apk to: gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/

$ gsutil --quiet cp ../test_app/apks/app-debug.apk gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/
Uploading: ../test_app/apks/app-debug-androidTest.apk to: gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/

$ gsutil --quiet cp ../test_app/apks/app-debug-androidTest.apk gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/
1 shards will be executed on: NexusLowRes

Executing shard 0:  com.example.app.ExampleInstrumentedTest#useAppContext

$ gcloud firebase test android run --type instrumentation --app gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug.apk --test gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug-androidTest.apk --results-bucket gs://delta-essence-114723-flank --device-ids NexusLowRes --os-version-ids 25 --locales en --orientations portrait --timeout 5m --results-dir 2017-06-01_23:01:58.278000_WOYW --test-targets class com.example.app.ExampleInstrumentedTest#useAppContext,
+---------+----------------------------+---------------------+
| OUTCOME |      TEST_AXIS_VALUE       |     TEST_DETAILS    |
+---------+----------------------------+---------------------+
| Passed  | NexusLowRes-25-en-portrait | 1 test cases passed |
+---------+----------------------------+---------------------+

Have questions, feedback, or issues? Get support by visiting:
  https://firebase.google.com/support/

Uploading [gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug.apk] to Firebase Test Lab...
Uploading [gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug-androidTest.apk] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/]

Test [matrix-2qkakwh64j8z8] has been created in the Google Cloud.
Firebase Test Lab will execute your instrumentation test on 1 device(s).
Creating individual test executions...
...done.

Test results will be streamed to [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/7892556729789863020].
19:02:09 Test is Pending
19:02:34 Starting attempt 1
19:02:34 Test is Running
19:03:47 Logging into the device
19:03:47 Installing APK: com.example.app
19:03:59 Installing APK: com.example.app.test
19:04:11 Running instrumentation test. Package: com.example.app.test testrunner: android.support.test.runner.AndroidJUnitRunner options: [key: CLASS
val: "com.example.app.ExampleInstrumentedTest#useAppContext"
]
19:04:25 Instrumentation test has finished
19:04:25 Retrieving performance samples
19:05:14 Retrieving test artifacts
19:05:26 Retrieving any crash results
19:05:50 Retrieving logcat
19:06:15 Done. Test time=7 (secs)
19:06:15 Test is Finished

Instrumentation testing complete.

More details are available at [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/7892556729789863020].
Test(s): com.example.app.ExampleInstrumentedTest#useAppContext
+---------+----------------------------+---------------------+
| OUTCOME |      TEST_AXIS_VALUE       |     TEST_DETAILS    |
+---------+----------------------------+---------------------+
| Passed  | NexusLowRes-25-en-portrait | 1 test cases passed |
+---------+----------------------------+---------------------+

More details are available at [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/7892556729789863020].


Fetching results to: /code/flank/Flank/results

$ gsutil --quiet -m cp -r -U gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/**/*.xml /code/flank/Flank/results
$ gsutil --quiet rm -r gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug.apk
$ gsutil --quiet rm -r gs://delta-essence-114723-flank/2017-06-01_23:01:58.278000_WOYW/app-debug-androidTest.apk
$ gsutil --quiet cp flank.tests gs://delta-essence-114723-flank/
Combined test execution time: ~0 minutes

End time: 2017-06-01_07:06
```

### CODE REVIEW

**Comment by renas** [comment]
In fetchXMLFiles we can't have it quiet as its from there we get the device name that we add to the xml results.

**Comment by bootstraponline** [comment]
```
$ gsutil -m cp -r -U gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/**/*.xml /Users/medwards/code/flank_tmp/results
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1011585040776239709.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_125957432179838360.xml...
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1353797233901014018.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1482722238301932061.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1505838201577055216.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1730927798758942742.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1838583013052727538.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1884360778823227563.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1916515317966787527.xml...
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_1998751863581007892.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_221647640038068946.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_2446147935510406695.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_2562846923107142552.xml...
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_2789891186006246504.xml...
Copying gs://delta-essence-114723-flank/2017-06-01_21:14:09.255000_WjQE/NexusLowRes-25-en-portrait/test_result_2515704412780213979.xml...
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [0/113 files][    0.0 B/  2.1 MiB]   0% Done
/ [1/113 files][ 23.8 KiB/  2.1 MiB]   1% Done
/ [2/113 files][ 47.7 KiB/  2.1 MiB]   2% Done
/ [2/113 files][ 71.4 KiB/  2.1 MiB]   3% Done
/ [3/113 files][ 95.2 KiB/  2.1 MiB]   4% Done
/ [4/113 files][ 95.2 KiB/  2.1 MiB]   4% Done
/ [4/113 files][ 95.2 KiB/  2.1 MiB]   4% Done
-
- [4/113 files][119.0 KiB/  2.1 MiB]   5% Done
- [4/113 files][119.0 KiB/  2.1 MiB]   5% Done
- [5/113 files][119.0 KiB/  2.1 MiB]   5% Done
- [5/113 files][119.0 KiB/  2.1 MiB]   5% Done
- [6/113 files][166.6 KiB/  2.1 MiB]   7% Done
- [7/113 files][166.6 KiB/  2.1 MiB]   7% Done
- [7/113 files][190.4 KiB/  2.1 MiB]   8% Done
- [8/113 files][190.4 KiB/  2.1 MiB]   8% Done
- [8/113 files][190.4 KiB/  2.1 MiB]   8% Done
- [9/113 files][238.0 KiB/  2.1 MiB]  10% Done
- [10/113 files][238.0 KiB/  2.1 MiB]  10% Done
- [10/113 files][238.0 KiB/  2.1 MiB]  10% Done
- [10/113 files][238.0 KiB/  2.1 MiB]  10% Done
- [10/113 files][238.0 KiB/  2.1 MiB]  10% Done
- [11/113 files][261.8 KiB/  2.1 MiB]  11% Done
- [11/113 files][262.1 KiB/  2.1 MiB]  11% Done
- [12/113 files][285.9 KiB/  2.1 MiB]  13% Done
- [13/113 files][285.9 KiB/  2.1 MiB]  13% Done
- [13/113 files][285.9 KiB/  2.1 MiB]  13% Done
- [13/113 files][285.9 KiB/  2.1 MiB]  13% Done
- [14/113 files][357.3 KiB/  2.1 MiB]  16% Done
- [15/113 files][357.3 KiB/  2.1 MiB]  16% Done
- [16/113 files][357.3 KiB/  2.1 MiB]  16% Done
- [16/113 files][357.3 KiB/  2.1 MiB]  16% Done
- [17/113 files][387.2 KiB/  2.1 MiB]  17% Done
- [17/113 files][387.2 KiB/  2.1 MiB]  17% Done
- [17/113 files][387.2 KiB/  2.1 MiB]  17% Done
- [18/113 files][387.2 KiB/  2.1 MiB]  17% Done
- [19/113 files][411.0 KiB/  2.1 MiB]  18% Done
- [19/113 files][434.8 KiB/  2.1 MiB]  19% Done
- [19/113 files][434.8 KiB/  2.1 MiB]  19% Done
- [20/113 files][434.8 KiB/  2.1 MiB]  19% Done
- [20/113 files][434.8 KiB/  2.1 MiB]  19% Done
- [21/113 files][482.4 KiB/  2.1 MiB]  21% Done
- [22/113 files][482.4 KiB/  2.1 MiB]  21% Done
- [22/113 files][482.4 KiB/  2.1 MiB]  21% Done
- [22/113 files][506.3 KiB/  2.1 MiB]  23% Done
- [22/113 files][506.3 KiB/  2.1 MiB]  23% Done
- [23/113 files][506.3 KiB/  2.1 MiB]  23% Done
- [24/113 files][553.9 KiB/  2.1 MiB]  25% Done
- [25/113 files][553.9 KiB/  2.1 MiB]  25% Done
- [25/113 files][553.9 KiB/  2.1 MiB]  25% Done
- [25/113 files][577.8 KiB/  2.1 MiB]  26% Done
- [25/113 files][601.6 KiB/  2.1 MiB]  27% Done
- [26/113 files][601.6 KiB/  2.1 MiB]  27% Done
- [27/113 files][601.6 KiB/  2.1 MiB]  27% Done
- [28/113 files][631.3 KiB/  2.1 MiB]  28% Done
- [29/113 files][631.3 KiB/  2.1 MiB]  28% Done
- [29/113 files][631.3 KiB/  2.1 MiB]  28% Done
- [29/113 files][655.1 KiB/  2.1 MiB]  29% Done
- [30/113 files][655.1 KiB/  2.1 MiB]  29% Done
- [30/113 files][655.1 KiB/  2.1 MiB]  29% Done
- [30/113 files][655.1 KiB/  2.1 MiB]  29% Done
- [31/113 files][702.7 KiB/  2.1 MiB]  32% Done
- [31/113 files][702.7 KiB/  2.1 MiB]  32% Done
- [32/113 files][726.6 KiB/  2.1 MiB]  33% Done
- [33/113 files][726.6 KiB/  2.1 MiB]  33% Done
- [33/113 files][726.6 KiB/  2.1 MiB]  33% Done
- [33/113 files][726.6 KiB/  2.1 MiB]  33% Done
\
\ [33/113 files][750.7 KiB/  2.1 MiB]  34% Done
\ [34/113 files][774.5 KiB/  2.1 MiB]  35% Done
\ [35/113 files][774.5 KiB/  2.1 MiB]  35% Done
\ [36/113 files][774.5 KiB/  2.1 MiB]  35% Done
\ [36/113 files][774.8 KiB/  2.1 MiB]  35% Done
\ [37/113 files][774.8 KiB/  2.1 MiB]  35% Done
\ [37/113 files][774.8 KiB/  2.1 MiB]  35% Done
\ [37/113 files][774.8 KiB/  2.1 MiB]  35% Done
\ [38/113 files][798.6 KiB/  2.1 MiB]  36% Done
\ [38/113 files][798.6 KiB/  2.1 MiB]  36% Done
\ [39/113 files][859.9 KiB/  2.1 MiB]  39% Done
\ [40/113 files][859.9 KiB/  2.1 MiB]  39% Done
\ [40/113 files][859.9 KiB/  2.1 MiB]  39% Done
\ [41/113 files][859.9 KiB/  2.1 MiB]  39% Done
\ [42/113 files][883.7 KiB/  2.1 MiB]  40% Done
\ [42/113 files][907.5 KiB/  2.1 MiB]  41% Done
\ [43/113 files][931.3 KiB/  2.1 MiB]  42% Done
\ [43/113 files][931.6 KiB/  2.1 MiB]  42% Done
\ [44/113 files][931.6 KiB/  2.1 MiB]  42% Done
\ [44/113 files][931.6 KiB/  2.1 MiB]  42% Done
\ [44/113 files][931.6 KiB/  2.1 MiB]  42% Done
\ [45/113 files][931.6 KiB/  2.1 MiB]  42% Done
\ [45/113 files][955.4 KiB/  2.1 MiB]  43% Done
\ [46/113 files][955.4 KiB/  2.1 MiB]  43% Done
\ [46/113 files][979.1 KiB/  2.1 MiB]  44% Done
\ [46/113 files][ 1002 KiB/  2.1 MiB]  45% Done
\ [47/113 files][  1.0 MiB/  2.1 MiB]  46% Done
\ [48/113 files][  1.0 MiB/  2.1 MiB]  46% Done
\ [48/113 files][  1.0 MiB/  2.1 MiB]  46% Done
\ [49/113 files][  1.0 MiB/  2.1 MiB]  47% Done
|
| [50/113 files][  1.0 MiB/  2.1 MiB]  48% Done
| [50/113 files][  1.0 MiB/  2.1 MiB]  48% Done
| [51/113 files][  1.0 MiB/  2.1 MiB]  48% Done
| [51/113 files][  1.0 MiB/  2.1 MiB]  48% Done
| [52/113 files][  1.1 MiB/  2.1 MiB]  49% Done
| [52/113 files][  1.1 MiB/  2.1 MiB]  49% Done
| [52/113 files][  1.1 MiB/  2.1 MiB]  49% Done
| [53/113 files][  1.1 MiB/  2.1 MiB]  50% Done
| [53/113 files][  1.1 MiB/  2.1 MiB]  52% Done
| [54/113 files][  1.1 MiB/  2.1 MiB]  52% Done
| [55/113 files][  1.1 MiB/  2.1 MiB]  52% Done
| [56/113 files][  1.1 MiB/  2.1 MiB]  52% Done
| [56/113 files][  1.1 MiB/  2.1 MiB]  52% Done
| [57/113 files][  1.2 MiB/  2.1 MiB]  53% Done
| [58/113 files][  1.2 MiB/  2.1 MiB]  53% Done
| [58/113 files][  1.2 MiB/  2.1 MiB]  54% Done
| [59/113 files][  1.2 MiB/  2.1 MiB]  54% Done
| [59/113 files][  1.2 MiB/  2.1 MiB]  54% Done
| [60/113 files][  1.2 MiB/  2.1 MiB]  55% Done
| [61/113 files][  1.2 MiB/  2.1 MiB]  55% Done
| [61/113 files][  1.2 MiB/  2.1 MiB]  55% Done
| [61/113 files][  1.2 MiB/  2.1 MiB]  55% Done
| [62/113 files][  1.2 MiB/  2.1 MiB]  56% Done
| [62/113 files][  1.2 MiB/  2.1 MiB]  56% Done
| [63/113 files][  1.2 MiB/  2.1 MiB]  56% Done
| [63/113 files][  1.2 MiB/  2.1 MiB]  56% Done
| [63/113 files][  1.2 MiB/  2.1 MiB]  56% Done
| [63/113 files][  1.2 MiB/  2.1 MiB]  57% Done
| [63/113 files][  1.2 MiB/  2.1 MiB]  57% Done
| [64/113 files][  1.2 MiB/  2.1 MiB]  57% Done
| [64/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [65/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [65/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [66/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [67/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [67/113 files][  1.3 MiB/  2.1 MiB]  58% Done
| [67/113 files][  1.3 MiB/  2.1 MiB]  59% Done
| [68/113 files][  1.3 MiB/  2.1 MiB]  59% Done
| [69/113 files][  1.3 MiB/  2.1 MiB]  60% Done
| [69/113 files][  1.3 MiB/  2.1 MiB]  60% Done
| [69/113 files][  1.3 MiB/  2.1 MiB]  61% Done
| [69/113 files][  1.3 MiB/  2.1 MiB]  61% Done
| [70/113 files][  1.3 MiB/  2.1 MiB]  61% Done
| [70/113 files][  1.3 MiB/  2.1 MiB]  61% Done
| [71/113 files][  1.4 MiB/  2.1 MiB]  62% Done
| [71/113 files][  1.4 MiB/  2.1 MiB]  62% Done
/
/ [72/113 files][  1.4 MiB/  2.1 MiB]  65% Done
/ [72/113 files][  1.4 MiB/  2.1 MiB]  66% Done
/ [73/113 files][  1.4 MiB/  2.1 MiB]  66% Done
/ [74/113 files][  1.4 MiB/  2.1 MiB]  66% Done
/ [74/113 files][  1.4 MiB/  2.1 MiB]  66% Done
/ [74/113 files][  1.4 MiB/  2.1 MiB]  67% Done
/ [74/113 files][  1.4 MiB/  2.1 MiB]  67% Done
/ [75/113 files][  1.4 MiB/  2.1 MiB]  67% Done
/ [76/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [77/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [77/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [77/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [77/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [78/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [78/113 files][  1.5 MiB/  2.1 MiB]  69% Done
/ [79/113 files][  1.5 MiB/  2.1 MiB]  70% Done
/ [80/113 files][  1.6 MiB/  2.1 MiB]  72% Done
/ [80/113 files][  1.6 MiB/  2.1 MiB]  72% Done
/ [81/113 files][  1.6 MiB/  2.1 MiB]  72% Done
/ [81/113 files][  1.6 MiB/  2.1 MiB]  73% Done
/ [81/113 files][  1.6 MiB/  2.1 MiB]  73% Done
/ [82/113 files][  1.6 MiB/  2.1 MiB]  73% Done
/ [83/113 files][  1.6 MiB/  2.1 MiB]  74% Done
/ [83/113 files][  1.6 MiB/  2.1 MiB]  75% Done
/ [84/113 files][  1.6 MiB/  2.1 MiB]  75% Done
/ [84/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [85/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [85/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [86/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [86/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [86/113 files][  1.7 MiB/  2.1 MiB]  77% Done
/ [87/113 files][  1.7 MiB/  2.1 MiB]  78% Done
/ [88/113 files][  1.7 MiB/  2.1 MiB]  81% Done
/ [89/113 files][  1.7 MiB/  2.1 MiB]  81% Done
/ [90/113 files][  1.8 MiB/  2.1 MiB]  81% Done
/ [90/113 files][  1.8 MiB/  2.1 MiB]  82% Done
/ [91/113 files][  1.8 MiB/  2.1 MiB]  82% Done
/ [92/113 files][  1.8 MiB/  2.1 MiB]  82% Done
/ [92/113 files][  1.8 MiB/  2.1 MiB]  82% Done
/ [92/113 files][  1.8 MiB/  2.1 MiB]  82% Done
/ [93/113 files][  1.8 MiB/  2.1 MiB]  83% Done
/ [94/113 files][  1.8 MiB/  2.1 MiB]  83% Done
/ [95/113 files][  1.8 MiB/  2.1 MiB]  84% Done
/ [96/113 files][  1.8 MiB/  2.1 MiB]  85% Done
/ [97/113 files][  1.9 MiB/  2.1 MiB]  86% Done
/ [98/113 files][  1.9 MiB/  2.1 MiB]  87% Done
/ [99/113 files][  1.9 MiB/  2.1 MiB]  89% Done
/ [100/113 files][  1.9 MiB/  2.1 MiB]  89% Done
/ [101/113 files][  1.9 MiB/  2.1 MiB]  90% Done
/ [102/113 files][  2.0 MiB/  2.1 MiB]  91% Done
/ [103/113 files][  2.0 MiB/  2.1 MiB]  92% Done
/ [104/113 files][  2.0 MiB/  2.1 MiB]  92% Done
/ [105/113 files][  2.0 MiB/  2.1 MiB]  92% Done
/ [106/113 files][  2.0 MiB/  2.1 MiB]  93% Done
/ [107/113 files][  2.0 MiB/  2.1 MiB]  93% Done
-
- [108/113 files][  2.1 MiB/  2.1 MiB]  96% Done
- [109/113 files][  2.1 MiB/  2.1 MiB]  96% Done
- [110/113 files][  2.1 MiB/  2.1 MiB]  97% Done
- [111/113 files][  2.1 MiB/  2.1 MiB]  98% Done
- [112/113 files][  2.1 MiB/  2.1 MiB]  99% Done
- [113/113 files][  2.1 MiB/  2.1 MiB] 100% Done
Operation completed over 113 objects/2.1 MiB.
```

Is this ^ `fetchXMLFiles`?

**Comment by renas** [comment]
Yeah exactly

**Comment by bootstraponline** [comment]
Ok, that's the one I wanted to make quiet though. The log file is being spammed. There's no other way? I have removed `--quiet` from fetchXMLFiles for now.

**Comment by renas** [comment]
Hopefully you won't need to have debug=true after we get the quit mechanism
in. If there is anything you think we should add to the standard output
(thats only in debug mode now) we can do that too.

**Comment by renas** [comment]
LGTM

**Comment by bootstraponline** [comment]
Some ideas:
- detect this XML command and excluded it from the debug output
- find some other way of discovering the device name (maybe an additional list request)

On large suites or slow internet connections, the % progress bar output is painful.

**Pull request merged**
