### PR TITLE
Disable FAIL_ON_UNKNOWN_PROPERTIES for forward compatibility

### PR DESCRIPTION
**Pull request by narenkmanoharan**
This makes sure that any future additions to the XML by FTL does not break existing builds of flank and is more permissive in structure about deserialization of unknown properties.

### CODE REVIEW

**Comment by bootstraponline** [comment]
Thanks for the pull request! Please add a JUnit test that verifies no exception is thrown when an unknown XML property is present in the parsed XML.

Something like this, note the addition of `random="prop"`.

```
 val unknownXml= """
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
  <testsuite random="prop" name="EarlGreyExampleSwiftTests" tests="4" failures="1" errors="0" skipped="0" time="51.773" hostname="localhost">
    <testcase name="a()" classname="a" time="1.0" random="prop"/>
  </testsuite>
</testsuites>
        """.trimIndent()

val parsed= parseAllSuitesXml(unknownXml).xmlToString()
       
assertThat(parsed).isEqualTo(unknownXml)
```

**Comment by bootstraponline** [comment]
Merged. Thanks for contributing!

**Comment by pjakubczyk** [comment]
Release :) ?

**Comment by bootstraponline** [comment]
I'm working on it. The Bitrise GitHub release step is failing. 

FTL finished the rollback so you shouldn't be broken anymore.

**Comment by pjakubczyk** [comment]
yep I see FTL is passing. Thanks !

**Comment by pocmo** [comment]
It just started happening again for us? 🤔

**Comment by bootstraponline** [comment]
> It just started happening again for us?

The Firebase team had a mistake in the rollout. It should be resolved now.

**Pull request merged**
