### PR TITLE
Fixes #490 Rename testShards to maxTestShards

### LINKED ISSUE #490: Rename testShards to maxTestShards
testShards defines an upper limit for the amount of test shards to use

### PR DESCRIPTION
**Pull request by miguelslemos**
This PR rename testShards parameter to maxTestShards

Fix #490

### CODE REVIEW

**Comment by miguelslemos** [comment]
This PR is breaking change, should I make it retro compatibility or just bump a major version?

**Comment by bootstraponline** [comment]
Thanks for the pull request! I'll take a look at this today.

**Comment by bootstraponline** [comment]
The code looks great.

To make it easy for people to upgrade, I'd like to dynamically rewrite the `flank.yml` file. If we don't have an auto-migration strategy then this will break immediately after merging since they run from the snapshot.

What do you think of that approach? I can add the code for this if the scope is too large.

The idea would be to read in the input YAML (`flank.yml` or `flank.ios.yml`), detect any old keys `testShards`, and then rename those keys. After the file is rewritten to disk then Flank would proceed normally.

**Comment by bootstraponline** [comment]
I talked with the team and once https://github.com/TestArmada/flank/issues/515 is figured out then I'll merge this pull request. It's an open question how to best preserve backwards compatibility.

**Pull request merged**
