### PR TITLE
Fix apk bucket name

### PR DESCRIPTION
**Pull request by bootstraponline**

### CODE REVIEW

**Comment by renas** [comment]
Still getting an error:

Creating bucket: gs://2017-05-31_21:44:05.258000_UQUn

InvalidUrlError: Invalid bucket name in URL "2017-05-31_21:44:05.258000_UQUn".
Uploading: walmart-android-qa-debug.apk to bucket: gs://2017-05-31_21:44:05.258000_UQUn

ResumableUploadAbortException: 400 Invalid bucket name: '2017-05-31_21:44:05.258000_UQUn'

**Comment by bootstraponline** [comment]
ok, there's a different set of validation rules on bucket names vs object names.

- https://cloud.google.com/storage/docs/naming

> Buckets/android-teacher/2017-05-25_16:51:20.616122_pHkM/

on my firebase, it looks like ^

if we require the user to supply a root bucket name, then the apks can be uploaded into a bucket object. Currently flank is trying to upload directly to the gs root.

>bucketName.append(new Configurator().getTestTimeBucket());

^ that seems like an easy fix?

**Comment by bootstraponline** [comment]
I'll resume this work tomorrow since it's the end of my work day. we should probably add a simple android app apk/test apk to use for testing on Travis.

**Comment by renas** [comment]
Ok cool. Would be awesome if we add app/test apk:s. I'll try to add tests
ASAP. Thanks for being part of the project.

**Comment by bootstraponline** [comment]
What I'll do tomorrow is make a simple app & commit it to the repo. Then there will be a small shell script a person can run locally before contributing. This will exercise the basic happy path (ensuring a test runs successfully on Firebase). We can require the output to be pasted into pull requests to verify the tests pass.

It's not ideal because running the tests is still a manual process. However at least there's something that people can run. The next step would be populating Travis with the necessary credentials to run these tests automagically.

**Comment by renas** [comment]
Sounds good!

**Comment by bootstraponline** [comment]
@renas hey, this is ready for review.

```
$ ./e2e_test.sh
:clean
:compileJava
Note: /code/flank/Flank/src/main/java/com/walmart/otto/tools/ProcessBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources NO-SOURCE
:classes
:jar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 0.852 secs
+ java -jar ./build/libs/Flank-1.2.0.jar ../test_app/apks/app-debug.apk ../test_app/apks/app-debug-androidTest.apk

Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 seconds.
$ gsutil mb gs://delta-essence-114723-flank/
Creating gs://delta-essence-114723-flank/...
ServiceException: 409 Bucket delta-essence-114723-flank already exists.

Creating bucket: gs://delta-essence-114723-flank/

Uploading: ../test_app/apks/app-debug.apk to: gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/

$ gsutil --quiet cp ../test_app/apks/app-debug.apk gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/
Uploading: ../test_app/apks/app-debug-androidTest.apk to: gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/

$ gsutil --quiet cp ../test_app/apks/app-debug-androidTest.apk gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/
1 shards will be executed on: NexusLowRes

Executing shard 0:  com.example.app.ExampleInstrumentedTest#useAppContext

$ gcloud firebase test android run --type instrumentation --app gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug.apk --test gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug-androidTest.apk --results-bucket gs://delta-essence-114723-flank --device-ids NexusLowRes --os-version-ids 25 --locales en --orientations portrait --timeout 5m --results-dir 2017-06-01_18:30:33.669000_rYfb --test-targets class com.example.app.ExampleInstrumentedTest#useAppContext,
+---------+----------------------------+---------------------+
| OUTCOME |      TEST_AXIS_VALUE       |     TEST_DETAILS    |
+---------+----------------------------+---------------------+
| Passed  | NexusLowRes-25-en-portrait | 1 test cases passed |
+---------+----------------------------+---------------------+

Have questions, feedback, or issues? Get support by visiting:
  https://firebase.google.com/support/

Uploading [gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug.apk] to Firebase Test Lab...
Uploading [gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug-androidTest.apk] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/]

Test [matrix-2w8kfoxu2xu1z] has been created in the Google Cloud.
Firebase Test Lab will execute your instrumentation test on 1 device(s).
Creating individual test executions...
...done.

Test results will be streamed to [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/6630949062214494665].
14:30:44 Test is Pending
14:31:21 Starting attempt 1
14:31:21 Test is Running
14:32:22 Logging into the device
14:32:34 Installing APK: com.example.app
14:32:46 Installing APK: com.example.app.test
14:32:58 Running instrumentation test. Package: com.example.app.test testrunner: android.support.test.runner.AndroidJUnitRunner options: [key: CLASS
val: "com.example.app.ExampleInstrumentedTest#useAppContext"
]
14:33:11 Instrumentation test has finished
14:33:11 Retrieving performance samples
14:33:59 Retrieving test artifacts
14:34:12 Retrieving any crash results
14:34:36 Retrieving logcat
14:35:25 Done. Test time=7 (secs)
14:35:25 Test is Finished

Instrumentation testing complete.

More details are available at [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/6630949062214494665].
Test(s): com.example.app.ExampleInstrumentedTest#useAppContext
+---------+----------------------------+---------------------+
| OUTCOME |      TEST_AXIS_VALUE       |     TEST_DETAILS    |
+---------+----------------------------+---------------------+
| Passed  | NexusLowRes-25-en-portrait | 1 test cases passed |
+---------+----------------------------+---------------------+

More details are available at [https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/6630949062214494665].


Fetching results to: /code/flank/Flank/results

$ gsutil -m cp -r -U gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/**/*.xml /code/flank/Flank/results
Copying gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/NexusLowRes-25-en-portrait/test_result_5740185961488125767.xml...
/ [0/1 files][    0.0 B/  304.0 B]   0% Done
/ [1/1 files][  304.0 B/  304.0 B] 100% Done
Operation completed over 1 objects/304.0 B.
$ gsutil rm -r gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug.apk
Removing gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug.apk#1496341839440957...
/ [1 objects]
Operation completed over 1 objects.
$ gsutil rm -r gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug-androidTest.apk
Removing gs://delta-essence-114723-flank/2017-06-01_18:30:33.669000_rYfb/app-debug-androidTest.apk#1496341840094789...
/ [1 objects]
Operation completed over 1 objects.
$ gsutil --quiet cp flank.tests gs://delta-essence-114723-flank/
Combined test execution time: ~0 minutes

End time: 2017-06-01_02:35
```

**Comment by bootstraponline** [comment]
new_firebase_folder

**Comment by bootstraponline** [comment]
better_debug_output

**Comment by bootstraponline** [comment]
> There is a ServiceException in the log?

Yes, this is happening on master as well. `gsutil mb ` fails when the bucket already exists. Flank will always try to create the root bucket.

**Comment by renas** [comment]
Great stuff @bootstraponline. Thank you!

**Comment by bootstraponline** [comment]
Thanks. If there are any issues in my code, just ping me and I will investigate. I'm hoping that with the new e2e script, that'll be less common.

**Comment by renas** [comment]
Sure, will do.

**Pull request merged**
