### PR TITLE
Add uniqueBucketName to match gcloud SDK

### PR DESCRIPTION
**Pull request by bootstraponline**
#16

```
$ java -jar Flank-1.2.0.jar app.apk test.apk

Creating bucket: 2017-05-31_21:24:47.249000_zKzY

Uploading: app.apk to bucket: 2017-05-31_21:24:47.249000_zKzY

Uploading: test.apk to bucket: 2017-05-31_21:24:47.249000_zKzY
```

### CODE REVIEW

**Comment by renas** [comment]
Looks good! Thanks for contributing!

**Comment by bootstraponline** [comment]
Thanks!

**Comment by renas** [comment]
@bootstraponline getting this error:

Creating bucket: 2017-05-31_21:35:37.921000_CGjp

CommandException: "mb" command does not support "file://" URLs. Did you mean to use a gs:// URL?
Uploading: walmart-android-qa-debug.apk to bucket: 2017-05-31_21:35:37.921000_CGjp

**Comment by bootstraponline** [comment]
This is why we need tests in CI. I'll look into it. The naming convention is directly from the SDK. Maybe some other part of Flank needs to be updated as well?

**Comment by renas** [comment]
I think the issue is that this is missing: gs://

**Comment by bootstraponline** [comment]
yeah, i just noticed that.

**Comment by bootstraponline** [comment]
https://github.com/TestArmada/flank/pull/18

**Comment by renas** [comment]
Will temporary revert this. The other PR is still open and will be merged when the url is ok.

**Pull request merged**
