### PR TITLE
Google format

### LINKED ISSUE #24: IntelliJ Java lint warnings
The IntelliJ linter is picking up some weird Java issues. We should probably fix them. And then add linting to the Travis CI build.

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix #24

### CODE REVIEW

**Comment by renas** [comment]
Awesome! Will have a look first thing tomorrow :)

**Comment by renas** [comment]
We have conflicts here due to previous PR:s

**Comment by bootstraponline** [comment]
Conflicts resolved

**Comment by bootstraponline** [comment]
I think enforcing a standard style will help prevent conflicts going forward. 😄

**Comment by renas** [comment]
Awesome! LGTM

**Pull request merged**
