### PR TITLE
Make YamlConfig output platform specific.

### LINKED ISSUE #184: Kotlin | Print only YamlConfig specific to the platform
before:

```
YamlConfig
  projectId: 'my-project'
  appApk: '',
  testApk: '',
  xctestZip: './EarlGreyExampleSwiftTests.zip',
  rootGcsBucket: 'earlgrey-swift',
  autoGoogleLogin: 'true',
  useOrchestrator: true,
  disablePerformanceMetrics: false,
  disableVideoRecording: false,
  testTimeoutMinutes: 30,
  testShards: 1,
  testRuns: 1,
  waitForResults: true,
  testMethods: []
  limitBreak: false
```

after:

```
YamlConfig
  projectId: 'delta-essence-114723'
  xctestZip: './EarlGreyExampleSwiftTests.zip',
  rootGcsBucket: 'earlgrey-swift',
  disablePerformanceMetrics: false,
  disableVideoRecording: false,
  testTimeoutMinutes: 30,
  testRuns: 1,
  waitForResults: true,
  limitBreak: false
```

### PR DESCRIPTION
**Pull request by bradylarson**
Fix #184

### CODE REVIEW

**Comment by bootstraponline** [comment]
I think it'd be great to add a simple JUnit test to verify the iOS fields don't appear in Android and vice versa.

**Comment by bradylarson** [comment]
Good idea. I was looking at that earlier and didn't see any methods to tell which platform it was on. Should I just make the `iOS()` function in `YamlConfig.kt` public? Or is there a way I don't know about?

**Comment by bootstraponline** [comment]
> Should I just make the iOS() function in YamlConfig.kt public? Or is there a way I don't know about?

Yeah, that sounds fine.

**Comment by bootstraponline** [comment]
Merged. Thanks!

**Pull request merged**
