### PR TITLE
Add findbugs (./gradlew findbugsMain)

### PR DESCRIPTION
**Pull request by bootstraponline**

### CODE REVIEW

**Comment by bootstraponline** [comment]
CI is expected to fail since we have 19 warnings.

**Comment by renas** [comment]
LGTM

**Comment by renas** [comment]
Actually there is a conflict here

**Comment by bootstraponline** [comment]
Conflict resolved

**Comment by bootstraponline** [comment]
@renas thoughts on setting up a [project](https://github.com/TestArmada/flank/projects) on this repo to track issues in progress? then it'd be easy to see what's currently being worked on vs in the backlog

**Pull request merged**
